import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import staffRoutes from './staff.routes';
import clientRoutes from './client.routes';
import eventRoutes from './event.routes';
import shiftRoutes from './shift.routes';
import financeRoutes from './finance.routes';
import timesheetRoutes from './timesheet.routes';
import invoiceRoutes from './invoice.routes';
import uploadRoutes from './upload.routes';
import chatRoutes from './chat.routes';
import notificationRoutes from './notification.routes';
import dashboardRoutes from './dashboard.routes';
import pricingRoutes from './pricing.routes';
import analyticsRoutes from './analytics.routes';
import integrationRoutes from './integration.routes';
import databaseRoutes from './database.routes';
import roleRoutes from './role.routes';
import settingsRoutes from './settings.routes';
import supportRoutes from './support.routes';
import reviewRoutes from './review.routes';
import unavailabilityRoutes from './unavailability.routes';
import contentRoutes from './content.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/staff', staffRoutes);
router.use('/clients', clientRoutes);
router.use('/events', eventRoutes);
router.use('/shifts', shiftRoutes);
router.use('/finance', financeRoutes);
router.use('/timesheets', timesheetRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/upload', uploadRoutes);
router.use('/chat', chatRoutes);
router.use('/notifications', notificationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/pricing-config', pricingRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/integrations', integrationRoutes);
router.use('/database', databaseRoutes);
router.use('/roles', roleRoutes);
router.use('/settings', settingsRoutes);
router.use('/support', supportRoutes);
router.use('/reviews', reviewRoutes);
router.use('/unavailability', unavailabilityRoutes);
router.use('/content', contentRoutes);

export default router;
